version: "3"

services:

    influxdb:
      image: influxdb:latest
      restart: always
      ports:
        - "8083:8083"
        - "8086:8086"
        - "8090:8090"
      volumes:
        - ./influxdb/data:/var/lib/influxdb
        - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 1024M

    grafana:
      image: grafana/grafana:latest
      restart: always
      user: "0"
      ports:
        - "3000:3000"
      volumes:
        - ./grafana/data:/var/lib/grafana
        - ./grafana.ini:/etc/grafana/grafana.ini:ro
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 512M

